/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import Clases.Reserva;
import Clases.Venta;
import Datos.DatosSistemas;
import javax.swing.JOptionPane;
/**
 *
 * @author CRISTHOFER
 */
public class FrmVenta extends javax.swing.JFrame {

    /**
     * Creates new form FrmVenta
     */
    public FrmVenta() {
        initComponents();
        cargarReservas();
        cboModalidad.removeAllItems();
        cboModalidad.addItem("Contado");
        cboModalidad.addItem("Cuotas Directas");
    }
    
    public void cargarReservas() {

    cboReserva.removeAllItems();

    for (int i = 0;
            i < DatosSistemas.gestionReserva.getCantidad();
            i++) {

        Reserva reserva =
                DatosSistemas.gestionReserva.getReserva(i);

        if (reserva.getDepartamento().getEstado().equalsIgnoreCase("Reservado")) {

            cboReserva.addItem(
                    reserva.getDepartamento().getCodigo());

        }

    }

    }
    
    public void limpiar() {

    txtPrecio.setText("");

    txtCuotaInicial.setText("");

    txtNumeroCuotas.setText("");

    txtMontoCuota.setText("");

    }
    
    public void generarContrato(Venta venta) {

    String contrato = "";

    contrato += "=========================================\n";
    contrato += "     CONTRATO DE COMPRA - VENTA\n";
    contrato += "=========================================\n\n";

    contrato += "DATOS DEL CLIENTE\n";
    contrato += "DNI: " + venta.getReserva().getCliente().getDni() + "\n";
    contrato += "Nombre: "
            + venta.getReserva().getCliente().getNombres()
            + " "
            + venta.getReserva().getCliente().getApellidos() + "\n\n";

    contrato += "DATOS DEL PROYECTO\n";
    contrato += "Proyecto: "
            + venta.getReserva().getDepartamento().getProyecto().getNombreProyecto() + "\n";

    contrato += "Fecha estimada de entrega: "
            + venta.getReserva().getDepartamento().getProyecto().getFechaEntrega() + "\n\n";

    contrato += "DATOS DEL DEPARTAMENTO\n";
    contrato += "Código: "
            + venta.getReserva().getDepartamento().getCodigo() + "\n";

    contrato += "Precio Total: S/ "
            + venta.getPrecioTotal() + "\n\n";

    contrato += "MODALIDAD DE PAGO\n";
    contrato += venta.getModalidadPago() + "\n\n";

    if (venta.getModalidadPago().equalsIgnoreCase("Cuotas Directas")) {

        contrato += "Cuota Inicial: S/ "
                + venta.getCuotaInicial() + "\n";

        contrato += "Número de Cuotas: "
                + venta.getNumeroCuotas() + "\n";

        contrato += "Monto por Cuota: S/ "
                + venta.getMontoCuota() + "\n\n";

    }

    contrato += "=========================================\n";
    contrato += "   ¡GRACIAS POR SU COMPRA!\n";
    contrato += "=========================================";

    JOptionPane.showMessageDialog(
            this,
            contrato,
            "Contrato de Compra - Venta",
            JOptionPane.INFORMATION_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblModalidad = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        lblCuotaInicial = new javax.swing.JLabel();
        lblNumeroCuotas = new javax.swing.JLabel();
        lblMontoCuota = new javax.swing.JLabel();
        cboReserva = new javax.swing.JComboBox<>();
        cboModalidad = new javax.swing.JComboBox<>();
        txtPrecio = new javax.swing.JTextField();
        txtCuotaInicial = new javax.swing.JTextField();
        txtNumeroCuotas = new javax.swing.JTextField();
        txtMontoCuota = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaListado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("VentaDepartamento");

        lblModalidad.setText("ModalidadPago");

        lblPrecioTotal.setText("PrecioTotal:");

        lblCuotaInicial.setText("CuotaInicial:");

        lblNumeroCuotas.setText("NumeroCuotas:");

        lblMontoCuota.setText("MontoPorCuota");

        cboReserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito", "Financiamento Bancario" }));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtAreaListado.setColumns(20);
        txtAreaListado.setRows(5);
        jScrollPane1.setViewportView(txtAreaListado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnRegistrar)
                        .addGap(74, 74, 74)
                        .addComponent(btnBuscar)
                        .addGap(81, 81, 81)
                        .addComponent(btnListar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnLimpiar)
                        .addGap(82, 82, 82)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModalidad)
                                    .addComponent(lblPrecioTotal)
                                    .addComponent(lblCuotaInicial)
                                    .addComponent(cboReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNumeroCuotas)
                                    .addComponent(lblMontoCuota))
                                .addGap(19, 19, 19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCuotaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumeroCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModalidad)
                    .addComponent(cboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioTotal)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCuotaInicial)
                    .addComponent(txtCuotaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroCuotas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMontoCuota)
                            .addComponent(txtMontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(cboReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnListar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Reserva reserva =
            DatosSistemas.gestionReserva.getReserva(
                    cboReserva.getSelectedIndex());

    Venta venta = new Venta(
            reserva,
            cboModalidad.getSelectedItem().toString(),
            Double.parseDouble(txtPrecio.getText()));

    if (DatosSistemas.gestionVenta.registrar(venta)) {

        if (cboModalidad.getSelectedItem().toString().equalsIgnoreCase("Cuotas Directas")) {

            venta.setCuotaInicial(
                    Double.parseDouble(txtCuotaInicial.getText()));

            venta.setNumeroCuotas(
                    Integer.parseInt(txtNumeroCuotas.getText()));

            venta.setMontoCuota(
                    Double.parseDouble(txtMontoCuota.getText()));

        }

        JOptionPane.showMessageDialog(this,
                "Venta registrada correctamente.");
        generarContrato(venta);
        limpiar();
        cargarReservas();
    } else {

        JOptionPane.showMessageDialog(this,
                "No se pudo registrar la venta.");

    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Venta venta = DatosSistemas.gestionVenta.buscar(
            cboReserva.getSelectedItem().toString());

    if (venta != null) {

        cboModalidad.setSelectedItem(
                venta.getModalidadPago());

        txtPrecio.setText(
                String.valueOf(venta.getPrecioTotal()));

        txtCuotaInicial.setText(
                String.valueOf(venta.getCuotaInicial()));

        txtNumeroCuotas.setText(
                String.valueOf(venta.getNumeroCuotas()));

        txtMontoCuota.setText(
                String.valueOf(venta.getMontoCuota()));

    } else {

        JOptionPane.showMessageDialog(this,
                "Venta no encontrada.");

    }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        txtAreaListado.setText(
            DatosSistemas.gestionVenta.listar());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboModalidad;
    private javax.swing.JComboBox<String> cboReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuotaInicial;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblMontoCuota;
    private javax.swing.JLabel lblNumeroCuotas;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaListado;
    private javax.swing.JTextField txtCuotaInicial;
    private javax.swing.JTextField txtMontoCuota;
    private javax.swing.JTextField txtNumeroCuotas;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
